In [5]:
import ifcopenshell
import ifcopenshell.api.alignment
import ifcopenshell.geom as geom
from ifcopenshell import ifcopenshell_wrapper
import numpy as np

file = ifcopenshell.file(schema="IFC4X3_ADD2")
project = file.createIfcProject(Name="Test")
geometric_representation_context = ifcopenshell.api.context.add_context(file,context_type="Model")
axis_model_representation_subcontext = ifcopenshell.api.context.add_context(file,context_type="Model",context_identifier="Axis",target_view="MODEL_VIEW",parent=geometric_representation_context)    

coordinates = [(500.,2500.),(3340.0,  660.0),(4340.0, 5000.0),(7600.0, 4560.0),(8480.0, 2010.0)]
radii = [(1000.),(1250.),(950.)]
vpoints = [(0.0,100.0),(2000.,135.0),(5000.,105.),(7400.,153.),(9800.,105.),(12800.,90.)]
lengths = [(1600.),(1200.),(2000.),(800.)]

alignment = ifcopenshell.api.alignment.create_alignment_by_pi_method(file,"TestAlignment",coordinates,radii,vpoints,lengths,include_geometry=False)

horizontal_alignment = alignment.IsNestedBy[0].RelatedObjects[0]
assert horizontal_alignment.is_a("IfcAlignmentHorizontal")

segments = ifcopenshell.api.alignment.map_alignment_segments(file,horizontal_alignment)

#curve = file.by_type("IfcCompositeCurve")[0]
#print(curve)
settings = geom.settings()
#for segment in segments:
#    segment_fn = ifcopenshell_wrapper.map_shape(settings,segment.wrapped_data)
#    segment_evaluator = ifcopenshell_wrapper.function_item_evaluator(settings,segment_fn)
#    s = segment_evaluator.evaluate(0.0)
#    start = np.array(s)
#    print("Start")
#    print(start)
#    e = segment_evaluator.evaluate(segment.SegmentLength.wrappedValue)
#    end = np.array(e)
#    print("End")
#    print(end)

#print("----------------")

for i,segment in enumerate(segments[:-1]):
    print(f"i={i}")
    next_segment = segments[i+1]
    segment_fn = ifcopenshell_wrapper.map_shape(settings,segment.wrapped_data)
    segment_evaluator = ifcopenshell_wrapper.function_item_evaluator(settings,segment_fn)
    e = segment_evaluator.evaluate(segment.SegmentLength.wrappedValue)
    end = np.array(e)
    print("End Previous")
    print(end)

    next_segment_fn = ifcopenshell_wrapper.map_shape(settings,next_segment.wrapped_data)
    next_segment_evaluator = ifcopenshell_wrapper.function_item_evaluator(settings,next_segment_fn)
    s = next_segment_evaluator.evaluate(0.0)
    start = np.array(s)
    print("Start Next")
    print(start)




End Previous Segment
#65=IfcCurveSegment(.DISCONTINUOUS.,#64,IfcLengthMeasure(0.),IfcLengthMeasure(1956.78565411881),#62)
[[ 8.39252880e-01  5.43741302e-01  0.00000000e+00  2.45678565e+03]
 [-5.43741302e-01  8.39252880e-01  0.00000000e+00  2.50000000e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Start Current Segment
#72=IfcCurveSegment(.DISCONTINUOUS.,#71,IfcLengthMeasure(0.),IfcLengthMeasure(1919.22266700613),#69)
[[ 1.83925288e+000  5.43741302e-001 -8.17516255e-312  2.14223800e+003]
 [-5.43741302e-001  1.83925288e+000 -6.95166635e-310  1.43601482e+003]
 [-2.12199579e-314 -3.11367261e-313  2.00000000e+000 -8.17516228e-312]
 [-6.95166635e-310 -4.94065646e-324 -6.95165821e-310  2.00000000e+000]]

End Previous Segment
#72=IfcCurveSegment(.DISCONTINUOUS.,#71,IfcLengthMeasure(0.),IfcLengthMeasure(1919.22266700613),#69)
[[ 1.83925288e+000  5.43741302e-001 -8.17516254e-312  2.14223800e+003]
 [-5.4